version: '3.9'
services:
  db:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/
      - ./queries:/queries/
    ports:
      - '3306:3306'
    expose:
      - '3306'
# Names our volume
volumes:
  dbdata: